package com.softhaxi.insofth.dao;
// Generated Oct 1, 2014 4:11:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FinanceAccountGroup generated by hbm2java
 */
public class FinanceAccountGroup  implements java.io.Serializable {


     private String id;
     private Set accounts = new HashSet(0);
     private int main;
     private String name;
     private String remark;
     private int status;

    public FinanceAccountGroup() {
    }

	
    public FinanceAccountGroup(String id, int main, String name, int status) {
        this.id = id;
        this.main = main;
        this.name = name;
        this.status = status;
    }
    public FinanceAccountGroup(String id, Set accounts, int main, String name, String remark, int status) {
       this.id = id;
       this.accounts = accounts;
       this.main = main;
       this.name = name;
       this.remark = remark;
       this.status = status;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }
    public int getMain() {
        return this.main;
    }
    
    public void setMain(int main) {
        this.main = main;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
}


