package com.softhaxi.insofth.dao;
// Generated Oct 1, 2014 4:11:32 PM by Hibernate Tools 4.3.1



/**
 * Fnacty generated by hbm2java
 */
public class FinanceActivity  implements java.io.Serializable {
    public static Object INCOME;


     private int id;
     private FinanceAccount account;
     private int date;
     private float amount;
     private String category;
     private String subCategory;
     private String remark;
     private String payMethod;
     private String payeer;
     private float tax;

    public FinanceActivity() {
    }

    public FinanceActivity(FinanceAccount account, int date, float amount, String category, String payMethod) {
        this.account = account;
        this.date = date;
        this.amount = amount;
        this.category = category;
        this.payMethod = payMethod;
    }

    public FinanceActivity(int id, FinanceAccount account, int date, float amount, String category, String subCategory, String remark, String payMethod, String payeer, float tax) {
        this.id = id;
        this.account = account;
        this.date = date;
        this.amount = amount;
        this.category = category;
        this.subCategory = subCategory;
        this.remark = remark;
        this.payMethod = payMethod;
        this.payeer = payeer;
        this.tax = tax;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the account
     */
    public FinanceAccount getAccount() {
        return account;
    }

    /**
     * @param account the account to set
     */
    public void setAccount(FinanceAccount account) {
        this.account = account;
    }

    /**
     * @return the date
     */
    public int getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(int date) {
        this.date = date;
    }

    /**
     * @return the amount
     */
    public float getAmount() {
        return amount;
    }

    /**
     * @param amount the amount to set
     */
    public void setAmount(float amount) {
        this.amount = amount;
    }

    /**
     * @return the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * @return the subCategory
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * @param subCategory the subCategory to set
     */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the payMethod
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * @param payMethod the payMethod to set
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * @return the payeer
     */
    public String getPayeer() {
        return payeer;
    }

    /**
     * @param payeer the payeer to set
     */
    public void setPayeer(String payeer) {
        this.payeer = payeer;
    }

    /**
     * @return the tax
     */
    public float getTax() {
        return tax;
    }

    /**
     * @param tax the tax to set
     */
    public void setTax(float tax) {
        this.tax = tax;
    }
    
    
}


